EXE		=
LIB		= .a
OBJ		= .o

MAKE		= make
AR		= ar
ARFLAGS		= -ruv
CAT		= cat
CCS		= ?CC?
CCP		= mpicc
CCD		= ?CC?
CFLAGS		= ?CFLAGS? -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -DSCOTCH_RENAME_PARSER -DSCOTCH_PTHREAD -Drestrict=__restrict
CLIBFLAGS	=
LDFLAGS		= -lz -lm -lrt -lpthread
CP		= cp
LEX		= ?FLEX? -Pscotchyy -olex.yy.c
LN		= ln
MKDIR		= mkdir
MV		= mv
RANLIB		= ?RANLIB?
YACC		= ?YACC? -pscotchyy -b y
